name: Build source code and test it

on:
  push:
    branches:
      - renovate/**
  pull_request:
    branches: [ main ]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        id: install_code
        run: bun install --frozen-lockfile
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build
        id: build_code
        run: npm run verify:android
  build_ios:
    runs-on: macOS-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        id: install_code
        run: bun install --frozen-lockfile
      - name: Build
        id: build_code
        run: bun verify:ios
  web:
    runs-on: ubuntu-latest
    name: 'Build code and test'
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        id: install_code
        run: bun install --frozen-lockfile
      - name: Lint
        id: lint_code
        run: bun run lint
      - name: Build
        id: build_code
        run: bun rum build
      - name: Verify
        id: verify_code
        run: bun run verify:web
